// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGu6T_6jfWbTT_7mAm0yrC8-RK3vnX0iE',
    appId: '1:995559943678:web:c2462a3cfd2e11a755e4af',
    messagingSenderId: '995559943678',
    projectId: 'evently-app-fe6dd',
    authDomain: 'evently-app-fe6dd.firebaseapp.com',
    storageBucket: 'evently-app-fe6dd.firebasestorage.app',
    measurementId: 'G-6MM8L5990Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoMgBUkbCZSMN7saYClwmk_Se3IQq-Rp4',
    appId: '1:995559943678:android:ddb4a4cc49067a1755e4af',
    messagingSenderId: '995559943678',
    projectId: 'evently-app-fe6dd',
    storageBucket: 'evently-app-fe6dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4chWh6ai2uBNZ9jScUNRKMjYGwCXznRA',
    appId: '1:995559943678:ios:bb7a19ce2095b78a55e4af',
    messagingSenderId: '995559943678',
    projectId: 'evently-app-fe6dd',
    storageBucket: 'evently-app-fe6dd.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4chWh6ai2uBNZ9jScUNRKMjYGwCXznRA',
    appId: '1:995559943678:ios:bb7a19ce2095b78a55e4af',
    messagingSenderId: '995559943678',
    projectId: 'evently-app-fe6dd',
    storageBucket: 'evently-app-fe6dd.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGu6T_6jfWbTT_7mAm0yrC8-RK3vnX0iE',
    appId: '1:995559943678:web:a7441a5dfb52747c55e4af',
    messagingSenderId: '995559943678',
    projectId: 'evently-app-fe6dd',
    authDomain: 'evently-app-fe6dd.firebaseapp.com',
    storageBucket: 'evently-app-fe6dd.firebasestorage.app',
    measurementId: 'G-ZF75K053TN',
  );

}